name: Elixir CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '25.0'
        elixir-version: '1.14.4'

    - name: Install Dependencies
      run: mix deps.get

    - name: Run Linters
      run: mix format --check-formatted && mix credo --strict

    - name: Run Tests
      run: mix test

      env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: localhost
          # The default Redis port
          REDIS_PORT: 6379

    #- name: Build Docker Image
    #  run: docker build -t my-elixir-app .
